
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed8;

	private global::Gtk.Button button11;

	private global::Gtk.DrawingArea drawingarea2;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed8 = new global::Gtk.Fixed();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed8.Add(this.button11);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.button11]));
		w1.X = 733;
		w1.Y = 190;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.drawingarea2 = new global::Gtk.DrawingArea();
		this.drawingarea2.WidthRequest = 500;
		this.drawingarea2.HeightRequest = 500;
		this.drawingarea2.Name = "drawingarea2";
		this.fixed8.Add(this.drawingarea2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.drawingarea2]));
		w2.X = 118;
		w2.Y = 141;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
		this.fixed8.Add(this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.label1]));
		w3.X = 791;
		w3.Y = 289;
		this.Add(this.fixed8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1181;
		this.DefaultHeight = 899;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.DragDrop += new global::Gtk.DragDropHandler(this.OnDragDrop);
		this.button11.Clicked += new global::System.EventHandler(this.OnButton11Clicked);
		this.drawingarea2.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnDrawingarea2ButtonPressEvent);
	}
}
